use sales;
#Sales in 2020
select t.*,d.* from transactions t
join date d on d.date=t.order_date
where year=2020
order by 4 desc;

#Total revenue generated in a particular year
select sum(t.sales_amount) as total_revenue,d.year from transactions t
join date d on d.date=t.order_date
group by d.year;

#Total revenue generated by a particular market
select t.market_code,m.markets_name,sum(t.sales_amount) as total_revenue from transactions t
join markets m on t.market_code=m.markets_code
group by t.market_code
order by 3 desc;




#Total revenue generated by a particular market at a particular year
SELECT 
    t.market_code,
    m.markets_name,
    d.year,sum(t.sales_amount) as revenue
FROM
    transactions t
        JOIN
    date d ON d.date = t.order_date
        JOIN
    markets m ON m.markets_code = t.market_code
GROUP BY t.market_code , d.year
ORDER BY 1;

#Creating a CTE
with rolling(market_code,markets_name,year,revenue) as 
(SELECT 
    t.market_code,
    m.markets_name,
    d.year,sum(t.sales_amount) as revenue
FROM
    transactions t
        JOIN
    date d ON d.date = t.order_date
        JOIN
    markets m ON m.markets_code = t.market_code
GROUP BY t.market_code , d.year) select market_code,markets_name,year,revenue,sum(revenue) over(partition by market_code
order by market_code,year) as rolling_revenue from rolling
ORDER BY 1;

#Checking the Table to clean the table
select * from sales.transactions where currency = 'USD';

select * from sales.transactions where sales_amount<1;

select* from sales.transactions where profit_margin_percentage<0;



















